name: Release

on:
  push:
    branches:
      - main
      - rc

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Semantic Release Dependencies
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release --all-features
